[package]
name = "mxload"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mixr = { path = "../mixr" }
polymod = { git = "https://github.com/skyebird189/polymod" }