language = "C"

include_version = false
cpp_compat = true
style = "type"
include_guard = "CMIXR_H"

[struct]
rename_fields = "CamelCase"

[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true